
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:test;MODE=MYSQL;  #??????????
#    url: jdbc:h2:file:./db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql


cfg:
  ws-port: 8000